Price Authority and Timer Service updates
Agoric/documentation pull request #1022
Opened 2024-03-21 21:35 UTC by dckc

2024-03-21 22:11 UTC, dckc commented
This uses typedoc for @agoric/time ; LMK if that should be a separate PR or something.

I ran `yarn typedoc` in agoric-sdk using the `typedoc-plugin-markdown` plugin and then copied the files over here.

2024-03-21 22:36 UTC, Chris-Hibbert commented
Can we split out @agoric/time? Once it's separate, I'd like to ask for a half-hour to add some descriptions around `TimeMath`, and a few other things. This generated doc looks really nice, but it could be so much better.

2024-03-21 22:41 UTC, dckc commented
> Can we split out @agoric/time?

ok: #1024

2024-03-21 23:00 UTC, Chris-Hibbert requested changes

2024-03-21 23:00 UTC, Chris-Hibbert commented on main/reference/zoe-api/price-authority.md
I don't think this belongs under Zoe.  PriceQuote, too. PriceAuthorities could be under `Deployed Zoe Contracts`. As far as I'm concerned, it doesn't need a slot in the sidebar, it just has to be linkable.

Hmm.  There's a page for RatioMath but it's blank. I wonder what happened there.

2024-03-22 19:28 UTC, dckc commented on main/reference/zoe-api/price-authority.md
> +• **registerPriceAuthority**: (`pa`: `ERef`\<`PriceAuthority`\>, `brandIn`: `Brand`\<`AssetKind`\>, `brandOut`: `Brand`\<`AssetKind`\>, `force?`: `boolean`) => `Promise`\<`Deleter`\>
ok; moving to separate page

2024-03-22 19:28 UTC, dckc commented on main/reference/zoe-api/price-authority.md
> +[priceAuthorityRegistry.js:27](https://github.com/Agoric/agoric-sdk/blob/a8c322206/packages/vats/src/priceAuthorityRegistry.js#L27)
This formatting comes from `typedoc`. I'd rather not mess with it. I hope it's less of a problem now that it's on a different page.

2024-03-22 19:37 UTC, dckc commented on main/reference/zoe-api/price-authority.md
> +## E(Deleter).delete()
If it needed more verbiage, I would think someone would have added some in the last 4 years...

https://github.com/Agoric/agoric-sdk/blob/0025f91195347f88b92cbbae39cbd9c40278aa38/packages/vats/src/priceAuthorityRegistry.js#L15-L18

In fact, I don't even see any tests.

https://github.com/Agoric/agoric-sdk/blob/a92cf556a0c806df293027458883f2a81a2bfade/packages/vats/test/test-priceAuthorityRegistry.js

Maybe we should demote it to undocumented?

2024-03-22 21:34 UTC, dckc commented on main/reference/zoe-api/price-authority.md
> I don't think this belongs under Zoe.

agreed.

> PriceAuthorities could be under `Deployed Zoe Contracts`.

Good idea! I added it there and changed the navigation around.
I didn't move `zoe-api/price-authority.md` because that involves redirects and stuff; we can do that later, perhaps.

2024-03-22 22:18 UTC, Chris-Hibbert commented on main/reference/zoe-api/price-authority.md
> +[priceAuthorityRegistry.js:27](https://github.com/Agoric/agoric-sdk/blob/a8c322206/packages/vats/src/priceAuthorityRegistry.js#L27)
It's enough less obvious.

2024-03-22 22:19 UTC, Chris-Hibbert approved these changes

2024-03-22 22:34 UTC, merged