Updated Index.md to fix broken image links
Agoric/documentation pull request #1023
Opened 2024-03-21 22:35 UTC by kbennett2000

2024-03-22 23:32 UTC, dckc requested changes
there seem to be some spurious edits in here

2024-03-22 23:32 UTC, dckc commented on main/guides/getting-started/index.md
> +yarn create @agoric/dapp --dapp-template dapp-offer-up demo
this looks like a regression

2024-03-22 23:32 UTC, dckc commented on main/guides/getting-started/index.md
> +This `start:contract` script will do a number of things that we will cover in more detail later <small>(_[transaction commands](../agoric-cli/agd-query-tx.md#transaction-commands), [permissioned depl
Why add the `.md`? Since the vitepress migration, CONTRIBUTING says to not use them.

2024-03-22 23:32 UTC, dckc commented on main/guides/getting-started/index.md
> -  _Note: [testnet deployment, faucets, etc.](../coreeval/local-testnet) are discussed later._
why delete this?

2024-07-26 13:12 UTC, amessbee commented
@dckc these instructions regarding docker seem outdated and unnecessary. Should we close this PR?

2024-07-27 16:05 UTC, closed without merging