fix: fix the dapp-agoric-basics page intro content
Agoric/documentation pull request #1119
Opened 2024-06-05 12:07 UTC by ansabgillani

Fix the intro for `dapp-agoric-basics` page

2024-06-07 16:53 UTC, Jovonni commented on main/guides/getting-started/tutorial-dapp-agoric-basics.md
> +In this tutorial you will install the `dapp-agoric-basics` dapp. This dapp is a collection of basic usecases of Agoric smart contract.
change ```usecases``` to ```use cases```

2024-06-07 16:55 UTC, Jovonni requested changes
minor commentary. Lgtm other then that. good stuff

2024-07-26 12:54 UTC, amessbee commented
@Jovonni if you approve this minor change, we can merge this right away!

2024-08-01 07:18 UTC, amessbee commented
This is not needed since changes are covered in #1166.

2024-08-01 07:18 UTC, closed without merging