adding a3p to glossary
Agoric/documentation pull request #1124
Opened 2024-06-11 16:53 UTC by Jovonni

adding a3p definition into glossary. Assuming it should go first

2024-06-11 16:59 UTC, dckc requested changes

2024-06-11 16:59 UTC, dckc commented on main/glossary/index.md
> +Acronym to refer to a proposal submitted on the agoric-3 mainnet
```suggestion
## a3p

A short form of [agoric-3-proposals](https://github.com/Agoric/agoric-3-proposals/), a repository containing "Proposals run or planned for Mainnet (agoric-3)". The resulting docker images supply a test network environment for dapps, as discussed in [getting started](/guides/getting-started/).
```

2024-06-11 17:03 UTC, Jovonni commented on main/glossary/index.md
> +Acronym to refer to a proposal submitted on the agoric-3 mainnet
i like it way better

2024-06-11 20:19 UTC, dckc approved these changes

2024-06-13 19:32 UTC, 0xpatrickdev approved these changes

2024-07-26 12:43 UTC, amessbee commented
@Jovonni let us merge this in spirit of our goal to minimize TODO stuff? :-)

2024-08-07 14:44 UTC, merged