docs: adding smart contract entry to glossary
Agoric/documentation pull request #1164
Opened 2024-07-26 13:35 UTC by amessbee

Adding a glossary entry for smart contracts.

**ref(s):**

[https://github.com/Agoric/documentation/issues/62](https://github.com/Agoric/documentation/issues/62)
[https://github.com/Agoric/agoric-sdk/issues/244](https://github.com/Agoric/agoric-sdk/issues/244)

2024-07-26 13:37 UTC, amessbee commented
@dckc please comment. I think I have added more than what was necessary, but I think the entry itself has to be there. I have deliberately added a line there in order to close #62 :-)

2024-07-26 22:27 UTC, dckc requested changes

2024-07-26 22:27 UTC, dckc commented on main/glossary/index.md
> +A smart contract is a self-executing contract with the terms of the agreement directly written into lines of code. These contracts are stored and executed on a blockchain network. Smart contracts aut
This is not the definition we use at Agoric.

Our definition is:

> A smart contract is a contract-like arrangement expressed in code, where the behavior of the program enforces the terms of the contract.

 - https://papers.agoric.com/smart-contracts-encyclopedia-entry/

2024-07-26 22:27 UTC, dckc commented on main/glossary/index.md
> +- Immutability: Once deployed on the blockchain, the contract code cannot be altered, ensuring that the terms remain consistent and tamper-proof.
we have governance, so not all our contracts are immutable

2024-07-28 06:36 UTC, amessbee commented
@dckc have a look at updates. Used text from the reference you provided this time.

2024-07-29 14:04 UTC, dckc requested changes

2024-07-29 14:04 UTC, dckc commented on main/glossary/index.md
> +State intervention.
I'd rather skip the commentary on social problems and State intervention in this context:

```suggestion
A smart contract is a contract-​like arrangement expressed in code, where the behavior of the 
program enforces the terms of the contract.
```

In general, the glossary shouldn't have novel content. The terms should be defined in sections that discuss them. Each glossary entry should be a short gloss with a link to the relevant section.

Here we have a link to `#offer-safety`, which is perhaps good enough. But better would be a link to [Smart Contract Basics](https://docs.agoric.com/guides/zoe/contract-basics.html#smart-contract-basics).

2024-07-29 16:10 UTC, dckc approved these changes

2024-07-30 10:22 UTC, merged