docs: closely held vs widely held
Agoric/documentation pull request #1248
Opened 2024-10-23 05:12 UTC by rabi-siddique

2024-10-23 15:50 UTC, dckc requested changes
"Resources" seems like a distraction. Let's not go there.

The links are suggestions; they would be nice but are not critical.

2024-10-23 15:50 UTC, dckc commented on main/guides/js-programming/hardened-js.md
> +#### Widely Shared Resources
"Resources"? Why introduce another term? Why not stick with "capabilities"?

2024-10-23 15:50 UTC, dckc commented on main/guides/js-programming/hardened-js.md
> +In the context of Agoric's object capability model, "widely shared" refers to resources or capabilities that are accessible to a large portion of the code within a system. For example:
This makes it sound like the term is not used outside of Agoric. It dates back at least as far as [Keykos](https://en.wikipedia.org/wiki/KeyKOS) in 1977

http://www.cap-lore.com/CapTheory/Glossary.html

2024-10-23 15:50 UTC, dckc commented on main/guides/js-programming/hardened-js.md
> +- **agoricNames**: This component serves as a read-only name service, which means it can be accessed by most parts of the system. Since it only allows data to be read and not modified, it poses minim
please link `agoricNames` to the more definitive description under Name Services

2024-10-23 15:50 UTC, dckc commented on main/guides/js-programming/hardened-js.md
> +- **agoricNamesAdmin**: Known as the write facet of the name service, this component allows modifications to the data in `agoricNames`. Given its capability to alter critical system data, access to `
likewise, link **agoricNamesAdmin**

2024-10-23 15:50 UTC, dckc commented on main/guides/js-programming/hardened-js.md
> +#### Widely Shared Resources
link the usages of the 2 terms under "access control with objects" please

> separation of powers between the publicFacet, which is expected to be shared widely, and the creatorFacet, which is closely held.

2024-10-23 16:23 UTC, rabi-siddique commented on main/guides/js-programming/hardened-js.md
> +In the context of Agoric's object capability model, "widely shared" refers to resources or capabilities that are accessible to a large portion of the code within a system. For example:
Wow. Thanks for sharing this!

2024-10-23 17:17 UTC, dckc commented on main/guides/js-programming/hardened-js.md
> +### [Widely Shared vs. Closely Held](/guides/zoe/contract-access-control.html#access-control-with-objects)
sorry; I meant the other way around: there are uses of these terms under "access control with objects". Please link those uses to the definitions here.

Also: Headings should not be links.

2024-10-24 04:56 UTC, rabi-siddique commented on main/guides/js-programming/hardened-js.md
> +### [Widely Shared vs. Closely Held](/guides/zoe/contract-access-control.html#access-control-with-objects)
I made the update. Lmk what you think

2024-10-24 13:36 UTC, dckc commented on main/guides/js-programming/hardened-js.md
> +  Similarly, in [Access Control with Objects](guides/zoe/contract-access-control.html#access-control-with-objects), this concept is mirrored by the **publicFacet**, which exposes safe-to-share functi
That works.

What I was suggesting, though, is links from uses to definitions, so that when the reader is in "Access Control with Objects" and comes across use of the terms "shared widely" and "closely held", they can follow links to definitions in this section. Just like the uses of agoricNames and agoricNamesAdmin are linked to definitions in "Name Services".

2024-10-24 13:47 UTC, rabi-siddique commented on main/guides/js-programming/hardened-js.md
> +  Similarly, in [Access Control with Objects](guides/zoe/contract-access-control.html#access-control-with-objects), this concept is mirrored by the **publicFacet**, which exposes safe-to-share functi
Ohh that makes sense. Let me update

2024-10-25 03:22 UTC, merged