chore: document changes to Zoe
Agoric/documentation pull request #553
Opened 2021-09-10 00:34 UTC by katelynsills

This PR documents:
* privateArgs
* offerArgs
* getInstallationForInstance
* Fees, fee purses, invitation fees, and metering

Closes #551

2021-09-10 17:39 UTC, Chris-Hibbert requested changes

2021-09-10 17:39 UTC, Chris-Hibbert commented on main/zoe/guide/contract-requirements.md
> +Your contract code must export a function `start()` as a non-default export. `zcf` is the Zoe Contract Facet and is the first argument provided to
Link `Zoe Contract Facet`.

2021-09-11 01:14 UTC, katelynsills commented on main/README.md
> +  <p>Ready for more? Check out <a href="/getting-started/intro-zoe.md">Zoe</a>. Zoe is responsible for enforcing what we call "offer safety", and the smart contract that runs on top of Zoe is respons
ah, good catch, this is html so the transformation from .md to .html isn't done.

2021-09-11 01:16 UTC, katelynsills commented on main/zoe/api/fees-and-metering.md
> +* `getPublicFacet`
I think we want to keep this document pretty minimal so we don't invest too much time with the large number of changes we have in the future. Argument parens sound good, but I think we shouldn't be investing in a lot of cross-links.

2021-09-11 01:21 UTC, katelynsills commented on main/zoe/api/fees-and-metering.md
> +  timeAuthority: chainTimerServiceP,
yeah, they will. I wasn't sure whether I should show what it looks like in the console/REPL or a more meaningful abstract version, but the version that was easily copy-and-pastable was the actual settings that fit the more meaningful abstract version.

2021-09-11 01:22 UTC, katelynsills commented on main/zoe/api/fees-and-metering.md
> +HIGH_FEE, and the expiry can be SHORT_EXP or LONG_EXPIRY.
ah yes, they are in the code. this is a mistake

2021-09-11 01:23 UTC, katelynsills commented on main/zoe/api/fees-and-metering.md
> +`highFee`, `shortExp`, and `longExp` in `zoeFeesConfig`.
No, it's passed into the function that makes Zoe.

2021-09-11 01:28 UTC, katelynsills commented on main/zoe/api/zoe.md
> +to handle any `offerArgs` passed to it or whether it drops them.
`offerArgs` is checked to be a copyRecord, but no additional checking is done. So the contract should feel safe interacting with the `offerArgs` object, but not its values.

2021-09-11 01:28 UTC, katelynsills commented on main/zoe/api/zoe.md
> +to handle any `offerArgs` passed to it or whether it drops them.
I'll add something to this effect

2021-09-11 01:41 UTC, katelynsills commented on main/zoe/api/fees-and-metering.md
> +# Fees and Metering
Good point, will add

2021-09-11 01:45 UTC, katelynsills commented on main/zoe/api/zoe.md
> +
I added some sub headings

2021-09-13 20:14 UTC, Chris-Hibbert approved these changes
This looks great! thanks for the update.

2021-09-13 21:02 UTC, merged