docs: Eject Hardened JavaScript docs
Agoric/documentation pull request #598
Opened 2021-12-23 19:26 UTC by kriskowal

The ejected docs will reappear in the Endo repository.

- docs: Eject Hardened JavaScript architecture topics
- fix: Vue config whitespace

2021-12-23 19:47 UTC, kriskowal commented
Pending upon https://github.com/endojs/endo/pull/965 and repointing references.

2021-12-23 23:12 UTC, dckc requested changes
a link to "Hardened JavaScript" when we're already in a Hardened JavaScript guide doesn't seem right.

2021-12-23 23:12 UTC, dckc commented on main/guides/js-programming/hardened-js.md
> +These compartments have `console` and `assert` globals from [Hardened JavaScript](https://github.com/endojs/endo/blob/master/packages/ses/README.md).
We're in the/a hardened js guide already. How about "the `ses` package" for the link text?

2021-12-24 00:06 UTC, dckc approved these changes
eject away

2021-12-24 02:00 UTC, merged