update quickstart docs
Agoric/documentation pull request #732
Opened 2022-12-01 15:37 UTC by cboydstun

requested by @dckc yesterday during office hours

2022-12-01 18:29 UTC, dckc submitted a review, later dismissed

2022-12-01 18:29 UTC, dckc commented on main/guides/getting-started/README.md
> +yarn link-cli ~/bin/agoric # creates an executable script for PATH reference
I'm not sure what "for PATH" is supposed to mean here.

```suggestion
yarn link-cli ~/bin/agoric # creates an executable script
```

We discuss `$PATH` in the expanded docs later in the page. The audience for this quickstart section is folks that already know norms such as PATH.

2022-12-05 16:18 UTC, Tyrosine22 requested changes
Dan's comment covers my suggested change to the PR.

2023-01-14 21:50 UTC, Tyrosine22 approved these changes

2023-06-24 05:07 UTC, merged